# Generated by Django 4.2.2 on 2025-05-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentifications", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="utilisateurs",
            options={},
        ),
        migrations.AddField(
            model_name="utilisateurs",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Photo de profil de l'utilisateur",
                null=True,
                upload_to="utilisateurs/photos/",
            ),
        ),
        migrations.AddField(
            model_name="utilisateurs",
            name="telephone",
            field=models.CharField(
                blank=True,
                help_text="Numéro de téléphone de l'utilisateur",
                max_length=10,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="utilisateurs",
            constraint=models.UniqueConstraint(
                condition=models.Q(("telephone", None), _negated=True),
                fields=("telephone",),
                name="unique_telephone_not_null",
            ),
        ),
    ]
