# Generated by Django 4.2.2 on 2025-06-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "authentifications",
            "0003_alter_utilisateurs_options_utilisateurs_photo_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateurs",
            name="pwd",
            field=models.CharField(
                blank=True, help_text="pwd de l'utilisateur", max_length=12, null=True
            ),
        ),
    ]
