# Generated by Django 4.2.2 on 2025-06-07 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("authentifications", "0004_utilisateurs_pwd"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoriqueConnexion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_evenement",
                    models.CharField(
                        choices=[
                            ("connexion", "Connexion"),
                            ("deconnexion", "Déconnexion"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_heure", models.DateTimeField(default=django.utils.timezone.now)),
                ("adresse_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
