# Generated by Django 4.2.2 on 2025-05-03 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotificationSMS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "types",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("relance_paiement", "Relance paiement"),
                            ("info_generale", "Information générale"),
                            ("alerte", "Alerte"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("destinataire", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("date_envoi", models.DateTimeField(auto_now_add=True)),
                ("envoye", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-date_envoi"],
            },
        ),
        migrations.CreateModel(
            name="TentativeEnvoi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_tentative", models.DateTimeField(auto_now_add=True)),
                ("succes", models.BooleanField(default=False)),
                ("message_erreur", models.TextField(blank=True, null=True)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tentatives",
                        to="sms.notificationsms",
                    ),
                ),
            ],
        ),
    ]
