# Generated by Django 4.2.2 on 2025-05-03 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("etablissements", "0001_initial"),
        ("cores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Matieres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("obligatoire", models.BooleanField(default=True)),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cores.cycles"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CoefficientMatieresEtablissements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coefficient", models.PositiveIntegerField(default=1)),
                (
                    "etablissement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="etablissements.etablissements",
                    ),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="matieres.matieres",
                    ),
                ),
                (
                    "niveau",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="etablissements.niveaux",
                    ),
                ),
            ],
            options={
                "unique_together": {("matiere", "niveau", "etablissement")},
            },
        ),
        migrations.CreateModel(
            name="CoefficientMatieres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coefficient", models.PositiveIntegerField(default=1)),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="matieres.matieres",
                    ),
                ),
                (
                    "niveau",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="etablissements.niveaux",
                    ),
                ),
            ],
            options={
                "unique_together": {("matiere", "niveau")},
            },
        ),
        migrations.CreateModel(
            name="CoefficientMatiereParPeriode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coefficient", models.PositiveIntegerField(default=1)),
                (
                    "etablissement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="etablissements.etablissements",
                    ),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="matieres.matieres",
                    ),
                ),
                (
                    "niveau",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="etablissements.niveaux",
                    ),
                ),
                (
                    "periode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cores.periodes"
                    ),
                ),
            ],
            options={
                "unique_together": {("matiere", "niveau", "etablissement", "periode")},
            },
        ),
    ]
