# Generated by Django 4.2.2 on 2025-05-17 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("etablissements", "0004_alter_etablissements_types"),
        ("matieres", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matieres",
            name="niveau",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="etablissements.niveaux",
            ),
        ),
    ]
