# Generated by Django 4.2.2 on 2025-05-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Eleves",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matricule", models.CharField(max_length=20, unique=True)),
                ("nom", models.CharField(max_length=100)),
                ("prenoms", models.CharField(max_length=100)),
                (
                    "sexe",
                    models.CharField(
                        choices=[("M", "Masculin"), ("F", "Féminin")], max_length=1
                    ),
                ),
                ("date_naissance", models.DateField()),
                (
                    "lieu_naissance",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="eleves/"),
                ),
            ],
            options={
                "verbose_name": "Élève",
                "verbose_name_plural": "Élèves",
            },
        ),
        migrations.CreateModel(
            name="Inscriptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("affecte", "Affecté"),
                            ("non_affecte", "Non Affecté"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_inscription", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LienParente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lien", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Mutations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_mutation", models.DateField()),
                ("motif", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Parents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_complet", models.CharField(max_length=150)),
                ("telephone", models.CharField(max_length=20)),
            ],
        ),
    ]
