# Generated by Django 4.2.2 on 2025-05-03 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("eleves", "0001_initial"),
        ("etablissements", "0001_initial"),
        ("cores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mutations",
            name="ancienne_classe",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ancienne_classe",
                to="etablissements.classes",
            ),
        ),
        migrations.AddField(
            model_name="mutations",
            name="eleve",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="eleves.eleves"
            ),
        ),
        migrations.AddField(
            model_name="mutations",
            name="nouvelle_classe",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nouvelle_classe",
                to="etablissements.classes",
            ),
        ),
        migrations.AddField(
            model_name="lienparente",
            name="eleve",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="eleves.eleves"
            ),
        ),
        migrations.AddField(
            model_name="lienparente",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="eleves.parents"
            ),
        ),
        migrations.AddField(
            model_name="inscriptions",
            name="annee_scolaire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cores.anneescolaires"
            ),
        ),
        migrations.AddField(
            model_name="inscriptions",
            name="classe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="etablissements.classes",
            ),
        ),
        migrations.AddField(
            model_name="inscriptions",
            name="eleve",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="eleves.eleves"
            ),
        ),
        migrations.AddField(
            model_name="inscriptions",
            name="utilisateur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="eleves",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="eleves.parents",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inscriptions",
            unique_together={("eleve", "annee_scolaire")},
        ),
    ]
