# Generated by Django 4.2.2 on 2025-05-05 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("eleves", "0003_alter_eleves_matricule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eleves",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="eleves.parents",
            ),
        ),
    ]
