# Generated by Django 4.2.2 on 2025-05-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eleves", "0004_alter_eleves_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eleves",
            name="matricule",
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
