# Generated by Django 4.2.2 on 2025-05-05 19:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eleves", "0005_alter_eleves_matricule"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eleves",
            options={},
        ),
    ]
