# Generated by Django 4.2.2 on 2025-05-05 19:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eleves", "0006_alter_eleves_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eleves",
            options={"verbose_name": "Élève", "verbose_name_plural": "Élèves"},
        ),
    ]
