# Generated by Django 4.2.2 on 2025-05-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eleves", "0007_alter_eleves_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="parents",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="parents",
            name="telephone",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
