# Generated by Django 4.2.2 on 2025-05-06 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("eleves", "0008_parents_email_alter_parents_telephone"),
    ]

    operations = [
        migrations.AddField(
            model_name="parents",
            name="utilisateur",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
