# Generated by Django 4.2.2 on 2025-05-06 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("scolarites", "0005_delete_relances"),
        ("eleves", "0009_parents_utilisateur"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scolarites",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_attribution", models.DateField(auto_now_add=True)),
                (
                    "inscription",
                    models.OneToOneField(
                        help_text="Lien unique avec l'inscription",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scolarite",
                        to="eleves.inscriptions",
                    ),
                ),
                (
                    "modalite",
                    models.ForeignKey(
                        blank=True,
                        help_text="Modalité de paiement applicable",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="scolarites.modalitepaiements",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Relances",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_relance", models.DateField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("envoyée", "Envoyée"),
                            ("reçue", "Reçue"),
                            ("ignorée", "Ignorée"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "echeance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scolarites.echeances",
                    ),
                ),
                (
                    "inscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eleves.inscriptions",
                    ),
                ),
            ],
        ),
    ]
