# Generated by Django 4.2.2 on 2025-05-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eleves", "0010_scolarites_relances"),
    ]

    operations = [
        migrations.AddField(
            model_name="relances",
            name="echeance_montant",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="relances",
            name="total_solde",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="relances",
            name="total_verse",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="relances",
            name="statut",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=50,
            ),
        ),
    ]
