# Generated by Django 4.2.2 on 2025-05-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eleves", "0011_relances_echeance_montant_relances_total_solde_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscriptions",
            name="etat",
            field=models.CharField(
                choices=[("Present", "Présent"), ("abandon", "Abandon")],
                default="Present",
                max_length=20,
            ),
        ),
    ]
