# Generated by Django 4.2.2 on 2025-05-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eleves", "0012_inscriptions_etat"),
    ]

    operations = [
        migrations.AddField(
            model_name="eleves",
            name="maladie_particuliere",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="eleves",
            name="nationalite",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
