# Generated by Django 4.2.2 on 2025-05-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eleves", "0013_eleves_maladie_particuliere_eleves_nationalite"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscriptions",
            name="Transport",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="inscriptions",
            name="cantine",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="inscriptions",
            name="reduction",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Réduction accordée (en montant, pas en %)",
                max_digits=8,
            ),
        ),
    ]
