# Generated by Django 4.2.2 on 2025-05-20 22:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eleves", "0014_inscriptions_transport_inscriptions_cantine_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inscriptions",
            old_name="Transport",
            new_name="transport",
        ),
    ]
