# Generated by Django 4.2.2 on 2025-05-21 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("eleves", "0015_rename_transport_inscriptions_transport"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvenementScolaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_evenement",
                    models.CharField(
                        choices=[
                            ("absence", "Absence"),
                            ("retard", "Retard"),
                            ("sanction", "Sanction"),
                            ("avertissement", "Avertissement"),
                            ("exclusion", "Exclusion temporaire"),
                            ("felicitation", "Félicitations"),
                            ("tableau_honneur", "Tableau d'honneur"),
                            ("activite", "Activité parascolaire"),
                            ("reunion", "Réunion parents-professeurs"),
                            ("conseil", "Conseil de classe"),
                            ("autre", "Autre"),
                        ],
                        max_length=30,
                    ),
                ),
                ("titre", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("date_evenement", models.DateField()),
                (
                    "responsable",
                    models.CharField(
                        help_text="Nom de la personne responsable (professeur, éducateur, etc.)",
                        max_length=100,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evenements",
                        to="eleves.eleves",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_evenement"],
            },
        ),
    ]
