# Generated by Django 4.2.2 on 2025-05-21 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cores", "0003_alter_anneescolaires_libelle"),
        ("eleves", "0016_evenementscolaire"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenementscolaire",
            name="annee_scolaire",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cores.anneescolaires",
            ),
        ),
    ]
