# Generated by Django 4.2.2 on 2025-06-07 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("etablissements", "0006_alter_emploitemps_professeur_and_more"),
        ("eleves", "0018_alter_evenementscolaire_annee_scolaire"),
    ]

    operations = [
        migrations.AddField(
            model_name="eleves",
            name="origine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="etablissements.etablissements",
            ),
        ),
    ]
