# Generated by Django 4.2.2 on 2025-06-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eleves", "0019_eleves_origine"),
    ]

    operations = [
        migrations.AddField(
            model_name="eleves",
            name="religion",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
