# Generated by Django 4.2.2 on 2025-05-03 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Classes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50)),
                ("capacite", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Niveaux",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50)),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cores.cycles"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Etablissements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                (
                    "types",
                    models.CharField(
                        choices=[("primaire", "Primaire"), ("college", "Collège")],
                        max_length=10,
                    ),
                ),
                ("adresse", models.TextField()),
                ("localisation", models.CharField(max_length=255)),
                ("code_etablissement", models.CharField(max_length=50, unique=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                (
                    "directeur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dirige",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmploiTemps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jour",
                    models.CharField(
                        choices=[
                            ("lundi", "Lundi"),
                            ("mardi", "Mardi"),
                            ("mercredi", "Mercredi"),
                            ("jeudi", "Jeudi"),
                            ("vendredi", "Vendredi"),
                            ("samedi", "Samedi"),
                        ],
                        max_length=10,
                    ),
                ),
                ("heure_debut", models.TimeField()),
                ("heure_fin", models.TimeField()),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="etablissements.classes",
                    ),
                ),
            ],
        ),
    ]
