# Generated by Django 4.2.2 on 2025-05-03 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("etablissements", "0001_initial"),
        ("enseignants", "0002_initial"),
        ("cores", "0001_initial"),
        ("matieres", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emploitemps",
            name="matiere",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="matieres.matieres"
            ),
        ),
        migrations.AddField(
            model_name="emploitemps",
            name="professeur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="enseignants.enseignants",
            ),
        ),
        migrations.AddField(
            model_name="classes",
            name="annee_scolaire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cores.anneescolaires"
            ),
        ),
        migrations.AddField(
            model_name="classes",
            name="etablissement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="etablissements.etablissements",
            ),
        ),
        migrations.AddField(
            model_name="classes",
            name="niveau",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="etablissements.niveaux"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="emploitemps",
            unique_together={("classe", "jour", "heure_debut")},
        ),
        migrations.AlterUniqueTogether(
            name="classes",
            unique_together={("nom", "etablissement", "annee_scolaire")},
        ),
    ]
