# Generated by Django 4.2.2 on 2025-05-04 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("etablissements", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeEtablissement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="etablissements",
            name="directeur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dirige",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="etablissements",
            name="types",
        ),
        migrations.AddField(
            model_name="etablissements",
            name="types",
            field=models.ManyToManyField(
                related_name="etablissements", to="etablissements.typeetablissement"
            ),
        ),
    ]
