# Generated by Django 4.2.2 on 2025-05-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cores", "0003_alter_anneescolaires_libelle"),
        (
            "etablissements",
            "0003_typeetablissement_alter_etablissements_directeur_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="etablissements",
            name="types",
            field=models.ManyToManyField(
                related_name="etablissements", to="cores.cycles"
            ),
        ),
    ]
