# Generated by Django 4.2.2 on 2025-05-30 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("enseignants", "0006_rename_enseignant_affectation_professseur"),
        ("etablissements", "0005_emploitemps_tennant_alter_emploitemps_professeur"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emploitemps",
            name="professeur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="enseignants.enseignants",
            ),
        ),
        migrations.AlterField(
            model_name="emploitemps",
            name="tennant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="enseignants.tenuedeclasse",
            ),
        ),
    ]
