# Generated by Django 4.2.2 on 2025-06-02 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cores", "0003_alter_anneescolaires_libelle"),
        ("etablissements", "0006_alter_emploitemps_professeur_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaisseCentrale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(default="Caisse Centrale", max_length=100)),
                ("solde_initial", models.PositiveIntegerField(default=0)),
                ("date_creation", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Caisses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("solde_initial", models.PositiveIntegerField(default=0)),
                ("date_creation", models.DateField(auto_now_add=True)),
                (
                    "annee_scolaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cores.anneescolaires",
                    ),
                ),
                (
                    "etablissement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="etablissements.etablissements",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caisse",
                "verbose_name_plural": "Caisses",
                "unique_together": {("etablissement", "annee_scolaire", "nom")},
            },
        ),
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_operation",
                    models.CharField(
                        choices=[("entree", "Entrée"), ("sortie", "Sortie")],
                        max_length=6,
                    ),
                ),
                ("motif", models.CharField(blank=True, max_length=100, null=True)),
                ("montant", models.PositiveIntegerField()),
                ("date_operation", models.DateField()),
                (
                    "justificatif",
                    models.FileField(blank=True, null=True, upload_to="justificatifs/"),
                ),
                ("commentaire", models.TextField(blank=True)),
                (
                    "annee_scolaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cores.anneescolaires",
                    ),
                ),
                (
                    "caisse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="caisses.caissecentrale",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Depenses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "motif",
                    models.CharField(
                        choices=[
                            ("tables", "Réparation de tables-bancs"),
                            ("iep", "Transport IEP"),
                            ("direction", "Transport école - Direction"),
                            ("admin", "Courses administratives"),
                            ("fournitures", "Achat fournitures"),
                            ("travaux", "Travaux divers"),
                            ("entretien", "Entretien des locaux"),
                        ],
                        max_length=100,
                    ),
                ),
                ("montant", models.PositiveIntegerField()),
                ("date_depense", models.DateField()),
                (
                    "justificatif",
                    models.FileField(blank=True, null=True, upload_to="justificatifs/"),
                ),
                (
                    "statut_validation",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente de validation"),
                            ("valide", "Validé"),
                            ("rejete", "Rejeté"),
                            ("partiel", "Partiellement validé"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("date_validation", models.DateTimeField(blank=True, null=True)),
                ("commentaire", models.TextField(blank=True)),
                (
                    "annee_scolaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cores.anneescolaires",
                    ),
                ),
                (
                    "caisse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="depenses",
                        to="caisses.caisses",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dépense",
                "verbose_name_plural": "Dépenses",
                "ordering": ["-date_depense"],
            },
        ),
    ]
