# Generated by Django 4.2.2 on 2025-06-02 21:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cores", "0003_alter_anneescolaires_libelle"),
        ("caisses", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CaisseCentrale",
            new_name="CaisseCentrales",
        ),
        migrations.RenameModel(
            old_name="Operation",
            new_name="Operations",
        ),
    ]
