# Generated by Django 4.2.2 on 2025-06-09 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("etablissements", "0006_alter_emploitemps_professeur_and_more"),
        ("caisses", "0002_rename_caissecentrale_caissecentrales_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operations",
            name="etablissement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="etablissements.etablissements",
            ),
        ),
    ]
