FONCTIONNALITES_PAR_DEFAUT = [
    "consulter_actualites",
    "ajouter_actualite",
    "modifier_actualite",
    "supprimer_actualite",
    "voir_eleves",
    "ajouter_eleve",
    "modifier_eleve",
    "supprimer_eleve",
    "voir_paiements",
    "ajouter_paiement",
    "generer_bulletin",
    # Ajoute ici toutes les fonctionnalités de ton système
]

#   @fonctionnalite_autorisee('liste_paiements_arrieres_back')  ==============================================================================

FONCTIONNALITES_PAR_ROLE = {
    'Administrateur': [
        {"fonctionnalite": "Accéder au tableau de bord", "code": "dashboard_tresorerie"},
        {"fonctionnalite": "Consulter la liste des établissements", "code": "etablissements_par_cycle"},
        {"fonctionnalite": "Ajouter un établissement", "code": "creer_etablissement"},
        {"fonctionnalite": "Modifier un établissement", "code": "modifier_etablissement"},
        {"fonctionnalite": "Supprimer un établissement", "code": "supprimer_etablissement"},
        {"fonctionnalite": "Consulter les détails d’un établissement", "code": "detail_etablissement"},
        {"fonctionnalite": "Consulter les frais de scolarité d’un établissement", "code": "liste_modalites_etablissement_back"},
        {"fonctionnalite": "Consulter les échéances associées aux frais de scolarité", "code": "detail_echeances_modalite_back"},
        {"fonctionnalite": "Modifier les échéances associées aux frais de scolarité", "code": "modifier_echeances_modalite"},
        
        {"fonctionnalite": "Consulter les frais de transport", "code": "modalites_transport"},
        {"fonctionnalite": "Ajouter un frais de transport", "code": "ajouter_modalite_transport"},
        {"fonctionnalite": "Modifier un frais de transport", "code": "modifier_modalite_transport"},
        {"fonctionnalite": "Supprimer un frais de transport", "code": "supprimer_modalite_transport"},
        
        {"fonctionnalite": "Consulter les frais de cantine", "code": "modalites_cantine"},
        {"fonctionnalite": "Ajouter un frais de cantine", "code": "ajouter_modalite_cantine"},
        {"fonctionnalite": "Modifier un frais de cantine", "code": "modifier_modalite_cantine"},
        {"fonctionnalite": "Supprimer un frais de cantine", "code": "supprimer_modalite_cantine"},
        
        {"fonctionnalite": "Consulter le personnel du Secrétariat Exécutif", "code": "liste_personnels_secretariat"},
        {"fonctionnalite": "Ajouter un membre du Secrétariat Exécutif", "code": "creer_personnel_secretariat"},
        {"fonctionnalite": "Modifier un membre du Secrétariat Exécutif", "code": "modifier_personnel_secretariat"},
        {"fonctionnalite": "Supprimer un membre du personnel", "code": "supprimer_personnel"},

        {"fonctionnalite": "Consulter le personnel de direction des établissements", "code": "liste_personnels_etablissement"},
        {"fonctionnalite": "Ajouter un membre de la direction", "code": "creer_personnel_direction"},
        {"fonctionnalite": "Modifier un membre de la direction", "code": "modifier_personnel_etablissement"},
        
        {"fonctionnalite": "Consulter le personnel de l’économat", "code": "liste_personnels_economat"},
        {"fonctionnalite": "Ajouter un membre de l’économat", "code": "creer_personnel_economat"},
        {"fonctionnalite": "Modifier un membre de l’économat", "code": "modifier_personnel_economat"},
        
        {"fonctionnalite": "Consulter le personnel instituteur", "code": "liste_personnels_instituteurs"},
        {"fonctionnalite": "Ajouter un instituteur", "code": "creer_personnel_adjoint"},
        {"fonctionnalite": "Modifier un instituteur", "code": "modifier_personnel_adjoint"},
        
        {"fonctionnalite": "Consulter le personnel professeur", "code": "liste_personnels_professeurs"},
        {"fonctionnalite": "Ajouter un professeur", "code": "creer_personnel_professeur"},
        {"fonctionnalite": "Modifier un professeur", "code": "modifier_personnel_professeur"},
        
        {"fonctionnalite": "Consulter les paiements des frais de scolarité", "code": "liste_paiements_back"},
        {"fonctionnalite": "Consulter les paiements des frais de transport", "code": "liste_paiements_back_transport"},
        {"fonctionnalite": "Consulter les paiements des frais de cantine", "code": "liste_paiements_back_cantine"},

        {"fonctionnalite": "Suivre les effectifs du Primaire", "code": "effectif_par_niveau_genre"},
        {"fonctionnalite": "Suivre les effectifs du Secondaire", "code": "effectif_par_niveau_genre_sec"},
        {"fonctionnalite": "Suivre les abandons – tous établissements", "code": "effectif_par_niveau_genre_abandon_tous_etablissements"},
        
        {"fonctionnalite": "Suivre la scolarité – tous établissements", "code": "tableau_etatscolarite_par_etablissement_secretariat"},
        {"fonctionnalite": "Suivre la scolarité secondaire – élèves affectés", "code": "tableau_etatscolarite_affecte_par_secretariat"},
        {"fonctionnalite": "Suivre la scolarité secondaire – élèves non affectés", "code": "tableau_etatscolarite_nonaffecte_par_secretariat"},
        {"fonctionnalite": "Suivre la scolarité – élèves présents", "code": "tableau_etatscolarite_pour_secretariat_classe_presents"},
        {"fonctionnalite": "Suivre la scolarité – élèves en abandon", "code": "tableau_etatscolarite_pour_secretariat_classe_abandons"},
        
        {"fonctionnalite": "Suivre les arriérés de scolarité", "code": "liste_paiements_arrieres_back"},
        {"fonctionnalite": "Consulter la liste des élèves en abandon", "code": "eleves_inscrits_abandon_tous"},
        {"fonctionnalite": "Consulter la liste des élèves bénéficiant d’une remise", "code": "eleves_inscrits_reduction_tous"},
        
        {"fonctionnalite": "Consulter la base de données des élèves", "code": "liste_eleves_back"},
        {"fonctionnalite": "Consulter la base de données des parents", "code": "liste_liens_back"},
        
        {"fonctionnalite": "Consulter les habilitations du Secrétariat Exécutif", "code": "liste_acces_secretariat"},
        {"fonctionnalite": "Modifier une habilitation", "code": "maj_acces_ajax"},
        
        {"fonctionnalite": "Consulter les habilitations de la direction d’établissement", "code": "liste_acces_etablissement"},
        {"fonctionnalite": "Consulter les habilitations de l’économat", "code": "liste_acces_economat"},
        {"fonctionnalite": "Consulter les habilitations des instituteurs/professeurs", "code": "liste_acces_personnels"},
        {"fonctionnalite": "Consulter les habilitations des parents", "code": "liste_acces_parent"},
        
        {"fonctionnalite": "Consulter les utilisateurs du Secrétariat Exécutif", "code": "liste_utilisateurs_secretariat"},
        {"fonctionnalite": "Modifier un utilisateur du Secrétariat Exécutif", "code": "modifier_utilisateur_secre"},
        {"fonctionnalite": "Réinitialiser le mot de passe d’un utilisateur", "code": "modifier_utilisateur_pwd"},
        {"fonctionnalite": "Activer ou désactiver un utilisateur", "code": "basculer_activation_utilisateur"},
        
        {"fonctionnalite": "Consulter les utilisateurs de la direction d’établissement", "code": "liste_utilisateurs_etablissement"},
        {"fonctionnalite": "Modifier un utilisateur de la direction d’établissement", "code": "modifier_utilisateur_direc"},
        {"fonctionnalite": "Consulter les utilisateurs de l’économat", "code": "liste_utilisateurs_economat"},
        {"fonctionnalite": "Modifier un utilisateur de l’économat", "code": "modifier_utilisateur_econo"},
        {"fonctionnalite": "Consulter les utilisateurs instituteurs/professeurs", "code": "liste_utilisateurs_personnel"},
        {"fonctionnalite": "Modifier un utilisateur instituteur/professeur", "code": "modifier_utilisateur_pers"},
        {"fonctionnalite": "Consulter les utilisateurs parents", "code": "liste_utilisateurs_parent"},
        {"fonctionnalite": "Modifier un utilisateur parent", "code": "modifier_utilisateur_pare"},
        
        {"fonctionnalite": "Effectuer une dotation de fonctionnement dans la caisse d’un établissement", "code": "enregistrer_dotation"},
        {"fonctionnalite": "Suivre les mouvements de caisse des établissements", "code": "liste_caisses"},
        {"fonctionnalite": "Consulter les détails d’une caisse d’établissement", "code": "detail_caisse"},
        {"fonctionnalite": "Consulter les dépenses en attente d’un établissement", "code": "liste_depenses_caisse"},
        {"fonctionnalite": "Traiter une dépense en attente", "code": "modifier_depense_back"},
        
        {"fonctionnalite": "Suivre les mouvements de la caisse principale", "code": "detail_caisse_principale"},
        {"fonctionnalite": "Ajouter une opération à la caisse principale", "code": "ajouter_operation"},
        {"fonctionnalite": "Modifier une opération dans la caisse principale", "code": "modifier_operation"},
        {"fonctionnalite": "Supprimer une opération dans la caisse principale", "code": "supprimer_operation"},
        {"fonctionnalite": "Consulter les opérations pour le point de caisse principale", "code": "liste_operations_points"},
        # ...
    ],
    'Enseignant': [
        {"fonctionnalite": "Saisir les notes", "code": "saisie_notes"},
        {"fonctionnalite": "Consulter les bulletins", "code": "consulter_bulletins"},
    ],
    
    'Secrétaire Exécutif': [
        {"fonctionnalite": "Accéder au tableau de bord", "code": "dashboard_tresorerie"},
        {"fonctionnalite": "Consulter la liste des établissements", "code": "etablissements_par_cycle"},
        {"fonctionnalite": "Ajouter un établissement", "code": "creer_etablissement"},
        {"fonctionnalite": "Modifier un établissement", "code": "modifier_etablissement"},
        {"fonctionnalite": "Supprimer un établissement", "code": "supprimer_etablissement"},
        {"fonctionnalite": "Consulter les détails d’un établissement", "code": "detail_etablissement"},
        {"fonctionnalite": "Consulter les frais de scolarité d’un établissement", "code": "liste_modalites_etablissement_back"},
        {"fonctionnalite": "Consulter les échéances associées aux frais de scolarité", "code": "detail_echeances_modalite_back"},
        {"fonctionnalite": "Modifier les échéances associées aux frais de scolarité", "code": "modifier_echeances_modalite"},
        
        {"fonctionnalite": "Consulter les frais de transport", "code": "modalites_transport"},
        {"fonctionnalite": "Ajouter un frais de transport", "code": "ajouter_modalite_transport"},
        {"fonctionnalite": "Modifier un frais de transport", "code": "modifier_modalite_transport"},
        {"fonctionnalite": "Supprimer un frais de transport", "code": "supprimer_modalite_transport"},
        
        {"fonctionnalite": "Consulter les frais de cantine", "code": "modalites_cantine"},
        {"fonctionnalite": "Ajouter un frais de cantine", "code": "ajouter_modalite_cantine"},
        {"fonctionnalite": "Modifier un frais de cantine", "code": "modifier_modalite_cantine"},
        {"fonctionnalite": "Supprimer un frais de cantine", "code": "supprimer_modalite_cantine"},
        
        {"fonctionnalite": "Consulter le personnel du Secrétariat Exécutif", "code": "liste_personnels_secretariat"},
        {"fonctionnalite": "Ajouter un membre du Secrétariat Exécutif", "code": "creer_personnel_secretariat"},
        {"fonctionnalite": "Modifier un membre du Secrétariat Exécutif", "code": "modifier_personnel_secretariat"},
        {"fonctionnalite": "Supprimer un membre du personnel", "code": "supprimer_personnel"},

        {"fonctionnalite": "Consulter le personnel de direction des établissements", "code": "liste_personnels_etablissement"},
        {"fonctionnalite": "Ajouter un membre de la direction", "code": "creer_personnel_direction"},
        {"fonctionnalite": "Modifier un membre de la direction", "code": "modifier_personnel_etablissement"},
        
        {"fonctionnalite": "Consulter le personnel de l’économat", "code": "liste_personnels_economat"},
        {"fonctionnalite": "Ajouter un membre de l’économat", "code": "creer_personnel_economat"},
        {"fonctionnalite": "Modifier un membre de l’économat", "code": "modifier_personnel_economat"},
        
        {"fonctionnalite": "Consulter le personnel instituteur", "code": "liste_personnels_instituteurs"},
        {"fonctionnalite": "Ajouter un instituteur", "code": "creer_personnel_adjoint"},
        {"fonctionnalite": "Modifier un instituteur", "code": "modifier_personnel_adjoint"},
        
        {"fonctionnalite": "Consulter le personnel professeur", "code": "liste_personnels_professeurs"},
        {"fonctionnalite": "Ajouter un professeur", "code": "creer_personnel_professeur"},
        {"fonctionnalite": "Modifier un professeur", "code": "modifier_personnel_professeur"},
        
        {"fonctionnalite": "Consulter les paiements des frais de scolarité", "code": "liste_paiements_back"},
        {"fonctionnalite": "Consulter les paiements des frais de transport", "code": "liste_paiements_back_transport"},
        {"fonctionnalite": "Consulter les paiements des frais de cantine", "code": "liste_paiements_back_cantine"},

        {"fonctionnalite": "Suivre les effectifs du Primaire", "code": "effectif_par_niveau_genre"},
        {"fonctionnalite": "Suivre les effectifs du Secondaire", "code": "effectif_par_niveau_genre_sec"},
        {"fonctionnalite": "Suivre les abandons – tous établissements", "code": "effectif_par_niveau_genre_abandon_tous_etablissements"},
        
        {"fonctionnalite": "Suivre la scolarité – tous établissements", "code": "tableau_etatscolarite_par_etablissement_secretariat"},
        {"fonctionnalite": "Suivre la scolarité secondaire – élèves affectés", "code": "tableau_etatscolarite_affecte_par_secretariat"},
        {"fonctionnalite": "Suivre la scolarité secondaire – élèves non affectés", "code": "tableau_etatscolarite_nonaffecte_par_secretariat"},
        {"fonctionnalite": "Suivre la scolarité – élèves présents", "code": "tableau_etatscolarite_pour_secretariat_classe_presents"},
        {"fonctionnalite": "Suivre la scolarité – élèves en abandon", "code": "tableau_etatscolarite_pour_secretariat_classe_abandons"},
        
        {"fonctionnalite": "Suivre les arriérés de scolarité", "code": "liste_paiements_arrieres_back"},
        {"fonctionnalite": "Consulter la liste des élèves en abandon", "code": "eleves_inscrits_abandon_tous"},
        {"fonctionnalite": "Consulter la liste des élèves bénéficiant d’une remise", "code": "eleves_inscrits_reduction_tous"},
        
        {"fonctionnalite": "Consulter la base de données des élèves", "code": "liste_eleves_back"},
        {"fonctionnalite": "Consulter la base de données des parents", "code": "liste_liens_back"},
        
        {"fonctionnalite": "Consulter les habilitations du Secrétariat Exécutif", "code": "liste_acces_secretariat"},
        {"fonctionnalite": "Modifier une habilitation", "code": "maj_acces_ajax"},
        
        {"fonctionnalite": "Consulter les habilitations de la direction d’établissement", "code": "liste_acces_etablissement"},
        {"fonctionnalite": "Consulter les habilitations de l’économat", "code": "liste_acces_economat"},
        {"fonctionnalite": "Consulter les habilitations des instituteurs/professeurs", "code": "liste_acces_personnels"},
        {"fonctionnalite": "Consulter les habilitations des parents", "code": "liste_acces_parent"},
        
        {"fonctionnalite": "Consulter les utilisateurs du Secrétariat Exécutif", "code": "liste_utilisateurs_secretariat"},
        {"fonctionnalite": "Modifier un utilisateur du Secrétariat Exécutif", "code": "modifier_utilisateur_secre"},
        {"fonctionnalite": "Réinitialiser le mot de passe d’un utilisateur", "code": "modifier_utilisateur_pwd"},
        {"fonctionnalite": "Activer ou désactiver un utilisateur", "code": "basculer_activation_utilisateur"},
        
        {"fonctionnalite": "Consulter les utilisateurs de la direction d’établissement", "code": "liste_utilisateurs_etablissement"},
        {"fonctionnalite": "Modifier un utilisateur de la direction d’établissement", "code": "modifier_utilisateur_direc"},
        {"fonctionnalite": "Consulter les utilisateurs de l’économat", "code": "liste_utilisateurs_economat"},
        {"fonctionnalite": "Modifier un utilisateur de l’économat", "code": "modifier_utilisateur_econo"},
        {"fonctionnalite": "Consulter les utilisateurs instituteurs/professeurs", "code": "liste_utilisateurs_personnel"},
        {"fonctionnalite": "Modifier un utilisateur instituteur/professeur", "code": "modifier_utilisateur_pers"},
        {"fonctionnalite": "Consulter les utilisateurs parents", "code": "liste_utilisateurs_parent"},
        {"fonctionnalite": "Modifier un utilisateur parent", "code": "modifier_utilisateur_pare"},
        
        {"fonctionnalite": "Effectuer une dotation de fonctionnement dans la caisse d’un établissement", "code": "enregistrer_dotation"},
        {"fonctionnalite": "Suivre les mouvements de caisse des établissements", "code": "liste_caisses"},
        {"fonctionnalite": "Consulter les détails d’une caisse d’établissement", "code": "detail_caisse"},
        {"fonctionnalite": "Consulter les dépenses en attente d’un établissement", "code": "liste_depenses_caisse"},
        {"fonctionnalite": "Traiter une dépense en attente", "code": "modifier_depense_back"},
        
        {"fonctionnalite": "Suivre les mouvements de la caisse principale", "code": "detail_caisse_principale"},
        {"fonctionnalite": "Ajouter une opération à la caisse principale", "code": "ajouter_operation"},
        {"fonctionnalite": "Modifier une opération dans la caisse principale", "code": "modifier_operation"},
        {"fonctionnalite": "Supprimer une opération dans la caisse principale", "code": "supprimer_operation"},
        {"fonctionnalite": "Consulter les opérations pour le point de caisse principale", "code": "liste_operations_points"},
    ],

    'Trésorerie': [
        {"fonctionnalite": "Accéder au tableau de bord", "code": "dashboard_tresorerie"},
        {"fonctionnalite": "Consulter la liste des établissements", "code": "etablissements_par_cycle"},
        {"fonctionnalite": "Ajouter un établissement", "code": "creer_etablissement"},
        {"fonctionnalite": "Modifier un établissement", "code": "modifier_etablissement"},
        {"fonctionnalite": "Supprimer un établissement", "code": "supprimer_etablissement"},
        {"fonctionnalite": "Consulter les détails d’un établissement", "code": "detail_etablissement"},
        {"fonctionnalite": "Consulter les frais de scolarité d’un établissement", "code": "liste_modalites_etablissement_back"},
        {"fonctionnalite": "Consulter les échéances associées aux frais de scolarité", "code": "detail_echeances_modalite_back"},
        {"fonctionnalite": "Modifier les échéances associées aux frais de scolarité", "code": "modifier_echeances_modalite"},
        
        {"fonctionnalite": "Consulter les frais de transport", "code": "modalites_transport"},
        {"fonctionnalite": "Ajouter un frais de transport", "code": "ajouter_modalite_transport"},
        {"fonctionnalite": "Modifier un frais de transport", "code": "modifier_modalite_transport"},
        {"fonctionnalite": "Supprimer un frais de transport", "code": "supprimer_modalite_transport"},
        
        {"fonctionnalite": "Consulter les frais de cantine", "code": "modalites_cantine"},
        {"fonctionnalite": "Ajouter un frais de cantine", "code": "ajouter_modalite_cantine"},
        {"fonctionnalite": "Modifier un frais de cantine", "code": "modifier_modalite_cantine"},
        {"fonctionnalite": "Supprimer un frais de cantine", "code": "supprimer_modalite_cantine"},
        
        {"fonctionnalite": "Consulter le personnel du Secrétariat Exécutif", "code": "liste_personnels_secretariat"},
        {"fonctionnalite": "Ajouter un membre du Secrétariat Exécutif", "code": "creer_personnel_secretariat"},
        {"fonctionnalite": "Modifier un membre du Secrétariat Exécutif", "code": "modifier_personnel_secretariat"},
        {"fonctionnalite": "Supprimer un membre du personnel", "code": "supprimer_personnel"},

        {"fonctionnalite": "Consulter le personnel de direction des établissements", "code": "liste_personnels_etablissement"},
        {"fonctionnalite": "Ajouter un membre de la direction", "code": "creer_personnel_direction"},
        {"fonctionnalite": "Modifier un membre de la direction", "code": "modifier_personnel_etablissement"},
        
        {"fonctionnalite": "Consulter le personnel de l’économat", "code": "liste_personnels_economat"},
        {"fonctionnalite": "Ajouter un membre de l’économat", "code": "creer_personnel_economat"},
        {"fonctionnalite": "Modifier un membre de l’économat", "code": "modifier_personnel_economat"},
        
        {"fonctionnalite": "Consulter le personnel instituteur", "code": "liste_personnels_instituteurs"},
        {"fonctionnalite": "Ajouter un instituteur", "code": "creer_personnel_adjoint"},
        {"fonctionnalite": "Modifier un instituteur", "code": "modifier_personnel_adjoint"},
        
        {"fonctionnalite": "Consulter le personnel professeur", "code": "liste_personnels_professeurs"},
        {"fonctionnalite": "Ajouter un professeur", "code": "creer_personnel_professeur"},
        {"fonctionnalite": "Modifier un professeur", "code": "modifier_personnel_professeur"},
        
        {"fonctionnalite": "Consulter les paiements des frais de scolarité", "code": "liste_paiements_back"},
        {"fonctionnalite": "Consulter les paiements des frais de transport", "code": "liste_paiements_back_transport"},
        {"fonctionnalite": "Consulter les paiements des frais de cantine", "code": "liste_paiements_back_cantine"},

        {"fonctionnalite": "Suivre les effectifs du Primaire", "code": "effectif_par_niveau_genre"},
        {"fonctionnalite": "Suivre les effectifs du Secondaire", "code": "effectif_par_niveau_genre_sec"},
        {"fonctionnalite": "Suivre les abandons – tous établissements", "code": "effectif_par_niveau_genre_abandon_tous_etablissements"},
        
        {"fonctionnalite": "Suivre la scolarité – tous établissements", "code": "tableau_etatscolarite_par_etablissement_secretariat"},
        {"fonctionnalite": "Suivre la scolarité secondaire – élèves affectés", "code": "tableau_etatscolarite_affecte_par_secretariat"},
        {"fonctionnalite": "Suivre la scolarité secondaire – élèves non affectés", "code": "tableau_etatscolarite_nonaffecte_par_secretariat"},
        {"fonctionnalite": "Suivre la scolarité – élèves présents", "code": "tableau_etatscolarite_pour_secretariat_classe_presents"},
        {"fonctionnalite": "Suivre la scolarité – élèves en abandon", "code": "tableau_etatscolarite_pour_secretariat_classe_abandons"},
        
        {"fonctionnalite": "Suivre les arriérés de scolarité", "code": "liste_paiements_arrieres_back"},
        {"fonctionnalite": "Consulter la liste des élèves en abandon", "code": "eleves_inscrits_abandon_tous"},
        {"fonctionnalite": "Consulter la liste des élèves bénéficiant d’une remise", "code": "eleves_inscrits_reduction_tous"},
        
        {"fonctionnalite": "Consulter la base de données des élèves", "code": "liste_eleves_back"},
        {"fonctionnalite": "Consulter la base de données des parents", "code": "liste_liens_back"},
        
        {"fonctionnalite": "Consulter les habilitations du Secrétariat Exécutif", "code": "liste_acces_secretariat"},
        {"fonctionnalite": "Modifier une habilitation", "code": "maj_acces_ajax"},
        
        {"fonctionnalite": "Consulter les habilitations de la direction d’établissement", "code": "liste_acces_etablissement"},
        {"fonctionnalite": "Consulter les habilitations de l’économat", "code": "liste_acces_economat"},
        {"fonctionnalite": "Consulter les habilitations des instituteurs/professeurs", "code": "liste_acces_personnels"},
        {"fonctionnalite": "Consulter les habilitations des parents", "code": "liste_acces_parent"},
        
        {"fonctionnalite": "Consulter les utilisateurs du Secrétariat Exécutif", "code": "liste_utilisateurs_secretariat"},
        {"fonctionnalite": "Modifier un utilisateur du Secrétariat Exécutif", "code": "modifier_utilisateur_secre"},
        {"fonctionnalite": "Réinitialiser le mot de passe d’un utilisateur", "code": "modifier_utilisateur_pwd"},
        {"fonctionnalite": "Activer ou désactiver un utilisateur", "code": "basculer_activation_utilisateur"},
        
        {"fonctionnalite": "Consulter les utilisateurs de la direction d’établissement", "code": "liste_utilisateurs_etablissement"},
        {"fonctionnalite": "Modifier un utilisateur de la direction d’établissement", "code": "modifier_utilisateur_direc"},
        {"fonctionnalite": "Consulter les utilisateurs de l’économat", "code": "liste_utilisateurs_economat"},
        {"fonctionnalite": "Modifier un utilisateur de l’économat", "code": "modifier_utilisateur_econo"},
        {"fonctionnalite": "Consulter les utilisateurs instituteurs/professeurs", "code": "liste_utilisateurs_personnel"},
        {"fonctionnalite": "Modifier un utilisateur instituteur/professeur", "code": "modifier_utilisateur_pers"},
        {"fonctionnalite": "Consulter les utilisateurs parents", "code": "liste_utilisateurs_parent"},
        {"fonctionnalite": "Modifier un utilisateur parent", "code": "modifier_utilisateur_pare"},
        
        {"fonctionnalite": "Effectuer une dotation de fonctionnement dans la caisse d’un établissement", "code": "enregistrer_dotation"},
        {"fonctionnalite": "Suivre les mouvements de caisse des établissements", "code": "liste_caisses"},
        {"fonctionnalite": "Consulter les détails d’une caisse d’établissement", "code": "detail_caisse"},
        {"fonctionnalite": "Consulter les dépenses en attente d’un établissement", "code": "liste_depenses_caisse"},
        {"fonctionnalite": "Traiter une dépense en attente", "code": "modifier_depense_back"},
        
        {"fonctionnalite": "Suivre les mouvements de la caisse principale", "code": "detail_caisse_principale"},
        {"fonctionnalite": "Ajouter une opération à la caisse principale", "code": "ajouter_operation"},
        {"fonctionnalite": "Modifier une opération dans la caisse principale", "code": "modifier_operation"},
        {"fonctionnalite": "Supprimer une opération dans la caisse principale", "code": "supprimer_operation"},
        {"fonctionnalite": "Consulter les opérations pour le point de caisse principale", "code": "liste_operations_points"},
    ],
    'Comptabilité': [
        {"fonctionnalite": "Accéder au tableau de bord", "code": "dashboard_tresorerie"},
        {"fonctionnalite": "Consulter la liste des établissements", "code": "etablissements_par_cycle"},
        {"fonctionnalite": "Ajouter un établissement", "code": "creer_etablissement"},
        {"fonctionnalite": "Modifier un établissement", "code": "modifier_etablissement"},
        {"fonctionnalite": "Supprimer un établissement", "code": "supprimer_etablissement"},
        {"fonctionnalite": "Consulter les détails d’un établissement", "code": "detail_etablissement"},
        {"fonctionnalite": "Consulter les frais de scolarité d’un établissement", "code": "liste_modalites_etablissement_back"},
        {"fonctionnalite": "Consulter les échéances associées aux frais de scolarité", "code": "detail_echeances_modalite_back"},
        {"fonctionnalite": "Modifier les échéances associées aux frais de scolarité", "code": "modifier_echeances_modalite"},
        
        {"fonctionnalite": "Consulter les frais de transport", "code": "modalites_transport"},
        {"fonctionnalite": "Ajouter un frais de transport", "code": "ajouter_modalite_transport"},
        {"fonctionnalite": "Modifier un frais de transport", "code": "modifier_modalite_transport"},
        {"fonctionnalite": "Supprimer un frais de transport", "code": "supprimer_modalite_transport"},
        
        {"fonctionnalite": "Consulter les frais de cantine", "code": "modalites_cantine"},
        {"fonctionnalite": "Ajouter un frais de cantine", "code": "ajouter_modalite_cantine"},
        {"fonctionnalite": "Modifier un frais de cantine", "code": "modifier_modalite_cantine"},
        {"fonctionnalite": "Supprimer un frais de cantine", "code": "supprimer_modalite_cantine"},
        
        {"fonctionnalite": "Consulter le personnel du Secrétariat Exécutif", "code": "liste_personnels_secretariat"},
        {"fonctionnalite": "Ajouter un membre du Secrétariat Exécutif", "code": "creer_personnel_secretariat"},
        {"fonctionnalite": "Modifier un membre du Secrétariat Exécutif", "code": "modifier_personnel_secretariat"},
        {"fonctionnalite": "Supprimer un membre du personnel", "code": "supprimer_personnel"},

        {"fonctionnalite": "Consulter le personnel de direction des établissements", "code": "liste_personnels_etablissement"},
        {"fonctionnalite": "Ajouter un membre de la direction", "code": "creer_personnel_direction"},
        {"fonctionnalite": "Modifier un membre de la direction", "code": "modifier_personnel_etablissement"},
        
        {"fonctionnalite": "Consulter le personnel de l’économat", "code": "liste_personnels_economat"},
        {"fonctionnalite": "Ajouter un membre de l’économat", "code": "creer_personnel_economat"},
        {"fonctionnalite": "Modifier un membre de l’économat", "code": "modifier_personnel_economat"},
        
        {"fonctionnalite": "Consulter le personnel instituteur", "code": "liste_personnels_instituteurs"},
        {"fonctionnalite": "Ajouter un instituteur", "code": "creer_personnel_adjoint"},
        {"fonctionnalite": "Modifier un instituteur", "code": "modifier_personnel_adjoint"},
        
        {"fonctionnalite": "Consulter le personnel professeur", "code": "liste_personnels_professeurs"},
        {"fonctionnalite": "Ajouter un professeur", "code": "creer_personnel_professeur"},
        {"fonctionnalite": "Modifier un professeur", "code": "modifier_personnel_professeur"},
        
        {"fonctionnalite": "Consulter les paiements des frais de scolarité", "code": "liste_paiements_back"},
        {"fonctionnalite": "Consulter les paiements des frais de transport", "code": "liste_paiements_back_transport"},
        {"fonctionnalite": "Consulter les paiements des frais de cantine", "code": "liste_paiements_back_cantine"},

        {"fonctionnalite": "Suivre les effectifs du Primaire", "code": "effectif_par_niveau_genre"},
        {"fonctionnalite": "Suivre les effectifs du Secondaire", "code": "effectif_par_niveau_genre_sec"},
        {"fonctionnalite": "Suivre les abandons – tous établissements", "code": "effectif_par_niveau_genre_abandon_tous_etablissements"},
        
        {"fonctionnalite": "Suivre la scolarité – tous établissements", "code": "tableau_etatscolarite_par_etablissement_secretariat"},
        {"fonctionnalite": "Suivre la scolarité secondaire – élèves affectés", "code": "tableau_etatscolarite_affecte_par_secretariat"},
        {"fonctionnalite": "Suivre la scolarité secondaire – élèves non affectés", "code": "tableau_etatscolarite_nonaffecte_par_secretariat"},
        {"fonctionnalite": "Suivre la scolarité – élèves présents", "code": "tableau_etatscolarite_pour_secretariat_classe_presents"},
        {"fonctionnalite": "Suivre la scolarité – élèves en abandon", "code": "tableau_etatscolarite_pour_secretariat_classe_abandons"},
        
        {"fonctionnalite": "Suivre les arriérés de scolarité", "code": "liste_paiements_arrieres_back"},
        {"fonctionnalite": "Consulter la liste des élèves en abandon", "code": "eleves_inscrits_abandon_tous"},
        {"fonctionnalite": "Consulter la liste des élèves bénéficiant d’une remise", "code": "eleves_inscrits_reduction_tous"},
        
        {"fonctionnalite": "Consulter la base de données des élèves", "code": "liste_eleves_back"},
        {"fonctionnalite": "Consulter la base de données des parents", "code": "liste_liens_back"},
        
        {"fonctionnalite": "Consulter les habilitations du Secrétariat Exécutif", "code": "liste_acces_secretariat"},
        {"fonctionnalite": "Modifier une habilitation", "code": "maj_acces_ajax"},
        
        {"fonctionnalite": "Consulter les habilitations de la direction d’établissement", "code": "liste_acces_etablissement"},
        {"fonctionnalite": "Consulter les habilitations de l’économat", "code": "liste_acces_economat"},
        {"fonctionnalite": "Consulter les habilitations des instituteurs/professeurs", "code": "liste_acces_personnels"},
        {"fonctionnalite": "Consulter les habilitations des parents", "code": "liste_acces_parent"},
        
        {"fonctionnalite": "Consulter les utilisateurs du Secrétariat Exécutif", "code": "liste_utilisateurs_secretariat"},
        {"fonctionnalite": "Modifier un utilisateur du Secrétariat Exécutif", "code": "modifier_utilisateur_secre"},
        {"fonctionnalite": "Réinitialiser le mot de passe d’un utilisateur", "code": "modifier_utilisateur_pwd"},
        {"fonctionnalite": "Activer ou désactiver un utilisateur", "code": "basculer_activation_utilisateur"},
        
        {"fonctionnalite": "Consulter les utilisateurs de la direction d’établissement", "code": "liste_utilisateurs_etablissement"},
        {"fonctionnalite": "Modifier un utilisateur de la direction d’établissement", "code": "modifier_utilisateur_direc"},
        {"fonctionnalite": "Consulter les utilisateurs de l’économat", "code": "liste_utilisateurs_economat"},
        {"fonctionnalite": "Modifier un utilisateur de l’économat", "code": "modifier_utilisateur_econo"},
        {"fonctionnalite": "Consulter les utilisateurs instituteurs/professeurs", "code": "liste_utilisateurs_personnel"},
        {"fonctionnalite": "Modifier un utilisateur instituteur/professeur", "code": "modifier_utilisateur_pers"},
        {"fonctionnalite": "Consulter les utilisateurs parents", "code": "liste_utilisateurs_parent"},
        {"fonctionnalite": "Modifier un utilisateur parent", "code": "modifier_utilisateur_pare"},
        
        {"fonctionnalite": "Effectuer une dotation de fonctionnement dans la caisse d’un établissement", "code": "enregistrer_dotation"},
        {"fonctionnalite": "Suivre les mouvements de caisse des établissements", "code": "liste_caisses"},
        {"fonctionnalite": "Consulter les détails d’une caisse d’établissement", "code": "detail_caisse"},
        {"fonctionnalite": "Consulter les dépenses en attente d’un établissement", "code": "liste_depenses_caisse"},
        {"fonctionnalite": "Traiter une dépense en attente", "code": "modifier_depense_back"},
        
        {"fonctionnalite": "Suivre les mouvements de la caisse principale", "code": "detail_caisse_principale"},
        {"fonctionnalite": "Ajouter une opération à la caisse principale", "code": "ajouter_operation"},
        {"fonctionnalite": "Modifier une opération dans la caisse principale", "code": "modifier_operation"},
        {"fonctionnalite": "Supprimer une opération dans la caisse principale", "code": "supprimer_operation"},
        {"fonctionnalite": "Consulter les opérations pour le point de caisse principale", "code": "liste_operations_points"},
    ],
    "Direction": [
        {"fonctionnalite": "Accéder au tableau de bord", "code": "dashboard_direction"},
        {"fonctionnalite": "Voir le détail d’un élève", "code": "detail_eleve"},
        {"fonctionnalite": "Enregistrer un paiement de scolarité", "code": "ajouter_paiement"},
        {"fonctionnalite": "Enregistrer un paiement de transport", "code": "transport_non_payees"},
        {"fonctionnalite": "Enregistrer un paiement de cantine", "code": "cantine_non_payees"},
        {"fonctionnalite": "Consulter la situation scolaire d’un élève (paiements)", "code": "detail_paiement"},
        {"fonctionnalite": "Voir les classes ayant des élèves inscrits", "code": "classes_avec_eleves_inscrits"},
        {"fonctionnalite": "Voir la liste des élèves d’une classe", "code": "liste_eleves_inscrits_par_classe"},
        {"fonctionnalite": "Consulter l’emploi du temps d’une classe", "code": "calendrier_emploi_classe"},
        {"fonctionnalite": "Créer un créneau dans l’emploi du temps (primaire)", "code": "creer_emploi_temps_primaire"},
        {"fonctionnalite": "Créer un créneau dans l’emploi du temps (collège)", "code": "creer_emploi_temps"},
        {"fonctionnalite": "Supprimer un créneau dans l’emploi du temps (collège)", "code": "supprimer_emploi"},
        {"fonctionnalite": "Modifier un créneau dans l’emploi du temps (collège)", "code": "modifier_emploi"},
        {"fonctionnalite": "Modifier un créneau dans l’emploi du temps (primaire)", "code": "modifier_emploi_primaire"},
        {"fonctionnalite": "Consulter les relances non à jour (par classe)", "code": "liste_relances_classe_non_a_jour"},
        {"fonctionnalite": "Ajouter des notes pour une classe", "code": "selectionner_matiere_periode"},
        {"fonctionnalite": "Voir les notes d’une classe", "code": "voir_notes_classe"},
        {"fonctionnalite": "Modifier les notes d’une classe", "code": "modifier_notes_classe"},
        {"fonctionnalite": "Créer une classe dans l’établissement", "code": "creer_classe_etablissement"},
        {"fonctionnalite": "Modifier une classe de l’établissement", "code": "modifier_classe_etablissement"},
        {"fonctionnalite": "Affecter les élèves inscrits à une classe", "code": "eleves_inscrits_etablissement"},
        {"fonctionnalite": "Voir la liste des matières de l’établissement", "code": "liste_matieres_etablissements"},
        {"fonctionnalite": "Voir la liste des enseignants de l’établissement", "code": "liste_enseignants"},
        {"fonctionnalite": "Ajouter une matière", "code": "ajouter_matiere"},
        {"fonctionnalite": "Affecter un enseignant responsable d’une classe", "code": "ajouter_tenue_de_classe"},
        {"fonctionnalite": "Consulter les paiements de scolarité", "code": "liste_paiements_etablissement"},
        {"fonctionnalite": "Consulter les paiements de transport", "code": "liste_paiements_etablissement_transport"},
        {"fonctionnalite": "Consulter les paiements de cantine", "code": "liste_paiements_etablissement_cantine"},
        {"fonctionnalite": "Consulter la synthèse des paiements de scolarité (par nature)", "code": "bilan_paiements_par_nature"},
        {"fonctionnalite": "Consulter la synthèse des paiements de transport (par nature)", "code": "bilan_paiements_par_nature_transport"},
        {"fonctionnalite": "Consulter la synthèse des paiements de cantine (par nature)", "code": "bilan_paiements_par_nature_cantine"},
        {"fonctionnalite": "Consulter les échéances de scolarité", "code": "liste_echeances_groupes"},
        {"fonctionnalite": "Consulter la liste des relances non à jour", "code": "liste_relances_non_a_jour"},
        {"fonctionnalite": "Suivre les effectifs des élèves", "code": "effectif_par_niveau_genre_etablissement"},
        {"fonctionnalite": "Suivre la scolarité – toutes les classes", "code": "tableau_etatscolarite_pour_etablissement_classe"},
        {"fonctionnalite": "Suivre la scolarité – élèves affectés", "code": "tableau_etatscolarite_pour_etablissement_classe_affecte"},
        {"fonctionnalite": "Suivre la scolarité – élèves non affectés", "code": "tableau_etatscolarite_pour_etablissement_classe_nonaffecte"},
        {"fonctionnalite": "Suivre les abandons – toutes les classes", "code": "effectif_par_niveau_genre_abandon_etablissement"},
        {"fonctionnalite": "Suivre la scolarité – élèves présents", "code": "tableau_etatscolarite_pour_etablissement_classe_presents"},
        {"fonctionnalite": "Suivre la scolarité – élèves en abandon", "code": "tableau_etatscolarite_pour_etablissement_classe_abandons"},
        {"fonctionnalite": "Suivre les arriérés de scolarité", "code": "liste_paiements_arrieres_etablissement"},
        {"fonctionnalite": "Voir la liste des élèves en abandon", "code": "eleves_inscrits_abandon_etablissement"},
        {"fonctionnalite": "Voir la liste des élèves ayant une remise", "code": "eleves_inscrits_reduction_etablissement"},
        {"fonctionnalite": "Suivre les mouvements de caisse", "code": "liste_caisses_etablissement"},
        {"fonctionnalite": "Ajouter une opération de caisse", "code": "ajouter_depense"},
        {"fonctionnalite": "Modifier une opération dans la caisse principale", "code": "modifier_operation"},
        {"fonctionnalite": "Supprimer une opération dans la caisse principale", "code": "supprimer_operation"},
        {"fonctionnalite": "Voir les opérations par point de caisse", "code": "liste_operations_points"},
        {"fonctionnalite": "Consulter la base des élèves de l’établissement", "code": "liste_eleves_etablissement_start"},
    ], 
    'Économat': [
        {"fonctionnalite": "Accéder au tableau de bord", "code": "dashboard_direction"},
        {"fonctionnalite": "Voir le détail d’un élève", "code": "detail_eleve"},
        {"fonctionnalite": "Enregistrer un paiement de scolarité", "code": "ajouter_paiement"},
        {"fonctionnalite": "Enregistrer un paiement de transport", "code": "transport_non_payees"},
        {"fonctionnalite": "Enregistrer un paiement de cantine", "code": "cantine_non_payees"},
        {"fonctionnalite": "Consulter la situation scolaire d’un élève (paiements)", "code": "detail_paiement"},
        {"fonctionnalite": "Voir les classes ayant des élèves inscrits", "code": "classes_avec_eleves_inscrits"},
        {"fonctionnalite": "Voir la liste des élèves d’une classe", "code": "liste_eleves_inscrits_par_classe"},
        {"fonctionnalite": "Consulter l’emploi du temps d’une classe", "code": "calendrier_emploi_classe"},
        {"fonctionnalite": "Créer un créneau dans l’emploi du temps (primaire)", "code": "creer_emploi_temps_primaire"},
        {"fonctionnalite": "Créer un créneau dans l’emploi du temps (collège)", "code": "creer_emploi_temps"},
        {"fonctionnalite": "Supprimer un créneau dans l’emploi du temps (collège)", "code": "supprimer_emploi"},
        {"fonctionnalite": "Modifier un créneau dans l’emploi du temps (collège)", "code": "modifier_emploi"},
        {"fonctionnalite": "Modifier un créneau dans l’emploi du temps (primaire)", "code": "modifier_emploi_primaire"},
        {"fonctionnalite": "Consulter les relances non à jour (par classe)", "code": "liste_relances_classe_non_a_jour"},
        {"fonctionnalite": "Ajouter des notes pour une classe", "code": "selectionner_matiere_periode"},
        {"fonctionnalite": "Voir les notes d’une classe", "code": "voir_notes_classe"},
        {"fonctionnalite": "Modifier les notes d’une classe", "code": "modifier_notes_classe"},
        {"fonctionnalite": "Créer une classe dans l’établissement", "code": "creer_classe_etablissement"},
        {"fonctionnalite": "Modifier une classe de l’établissement", "code": "modifier_classe_etablissement"},
        {"fonctionnalite": "Affecter les élèves inscrits à une classe", "code": "eleves_inscrits_etablissement"},
        {"fonctionnalite": "Voir la liste des matières de l’établissement", "code": "liste_matieres_etablissements"},
        {"fonctionnalite": "Voir la liste des enseignants de l’établissement", "code": "liste_enseignants"},
        {"fonctionnalite": "Ajouter une matière", "code": "ajouter_matiere"},
        {"fonctionnalite": "Affecter un enseignant responsable d’une classe", "code": "ajouter_tenue_de_classe"},
        {"fonctionnalite": "Consulter les paiements de scolarité", "code": "liste_paiements_etablissement"},
        {"fonctionnalite": "Consulter les paiements de transport", "code": "liste_paiements_etablissement_transport"},
        {"fonctionnalite": "Consulter les paiements de cantine", "code": "liste_paiements_etablissement_cantine"},
        {"fonctionnalite": "Consulter la synthèse des paiements de scolarité (par nature)", "code": "bilan_paiements_par_nature"},
        {"fonctionnalite": "Consulter la synthèse des paiements de transport (par nature)", "code": "bilan_paiements_par_nature_transport"},
        {"fonctionnalite": "Consulter la synthèse des paiements de cantine (par nature)", "code": "bilan_paiements_par_nature_cantine"},
        {"fonctionnalite": "Consulter les échéances de scolarité", "code": "liste_echeances_groupes"},
        {"fonctionnalite": "Consulter la liste des relances non à jour", "code": "liste_relances_non_a_jour"},
        {"fonctionnalite": "Suivre les effectifs des élèves", "code": "effectif_par_niveau_genre_etablissement"},
        {"fonctionnalite": "Suivre la scolarité – toutes les classes", "code": "tableau_etatscolarite_pour_etablissement_classe"},
        {"fonctionnalite": "Suivre la scolarité – élèves affectés", "code": "tableau_etatscolarite_pour_etablissement_classe_affecte"},
        {"fonctionnalite": "Suivre la scolarité – élèves non affectés", "code": "tableau_etatscolarite_pour_etablissement_classe_nonaffecte"},
        {"fonctionnalite": "Suivre les abandons – toutes les classes", "code": "effectif_par_niveau_genre_abandon_etablissement"},
        {"fonctionnalite": "Suivre la scolarité – élèves présents", "code": "tableau_etatscolarite_pour_etablissement_classe_presents"},
        {"fonctionnalite": "Suivre la scolarité – élèves en abandon", "code": "tableau_etatscolarite_pour_etablissement_classe_abandons"},
        {"fonctionnalite": "Suivre les arriérés de scolarité", "code": "liste_paiements_arrieres_etablissement"},
        {"fonctionnalite": "Voir la liste des élèves en abandon", "code": "eleves_inscrits_abandon_etablissement"},
        {"fonctionnalite": "Voir la liste des élèves ayant une remise", "code": "eleves_inscrits_reduction_etablissement"},
        {"fonctionnalite": "Suivre les mouvements de caisse", "code": "liste_caisses_etablissement"},
        {"fonctionnalite": "Ajouter une opération de caisse", "code": "ajouter_depense"},
        {"fonctionnalite": "Modifier une opération dans la caisse principale", "code": "modifier_operation"},
        {"fonctionnalite": "Supprimer une opération dans la caisse principale", "code": "supprimer_operation"},
        {"fonctionnalite": "Voir les opérations par point de caisse", "code": "liste_operations_points"},
        {"fonctionnalite": "Consulter la base des élèves de l’établissement", "code": "liste_eleves_etablissement_start"},
    ],#   @fonctionnalite_autorisee('liste_paiements_arrieres_back')  
    'Enseignants': [
        {"fonctionnalite": "Saisir les notes", "code": "saisie_notes"},
        {"fonctionnalite": "Consulter les bulletins", "code": "consulter_bulletins"},
    ],
    'Parents': [
        {"fonctionnalite": "Accéder au tableau de bord", "code": "dashboard_parent"},
        {"fonctionnalite": "Consulter les détails de ses enfants", "code": "detail_eleve_parent"},
        {"fonctionnalite": "Consulter les paiements liés à ses enfants", "code": "paiements_eleve"},
        {"fonctionnalite": "Voir la liste de ses enfants", "code": "liste_enfants"},
        {"fonctionnalite": "Consulter les bulletins de ses enfants", "code": "bulletins_eleve"},
    ],
 
    'Professeurs': [
        {"fonctionnalite": "Saisir les notes", "code": "saisie_notes"},
        {"fonctionnalite": "Consulter les bulletins", "code": "consulter_bulletins"},
    ],
}