# Generated by Django 4.2.2 on 2025-05-03 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("enseignants", "0001_initial"),
        ("eleves", "0001_initial"),
        ("cores", "0001_initial"),
        ("matieres", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valeur", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="eleves.eleves"
                    ),
                ),
                (
                    "enseignant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="enseignants.enseignants",
                    ),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="matieres.matieres",
                    ),
                ),
                (
                    "periode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cores.periodes"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bulletins",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moyenne_generale",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("rang", models.PositiveIntegerField()),
                ("appreciation", models.TextField()),
                ("mention", models.CharField(blank=True, max_length=20)),
                ("decision_conseil", models.TextField(blank=True)),
                ("fichier_pdf", models.FileField(upload_to="bulletins/")),
                (
                    "annee_scolaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cores.anneescolaires",
                    ),
                ),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="eleves.eleves"
                    ),
                ),
                (
                    "periode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cores.periodes"
                    ),
                ),
            ],
        ),
    ]
