# Generated by Django 4.2.2 on 2025-05-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cycles",
            name="code",
            field=models.CharField(max_length=2, null=True, unique=True),
        ),
    ]
