# Generated by Django 4.2.2 on 2025-06-08 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cores", "0003_alter_anneescolaires_libelle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="periodes",
            name="trimestre",
        ),
        migrations.AddField(
            model_name="periodes",
            name="cycle",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cores.cycles",
            ),
        ),
    ]
