# Generated by Django 4.2.2 on 2025-05-05 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import scolarites.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cores", "0003_alter_anneescolaires_libelle"),
        (
            "etablissements",
            "0003_typeetablissement_alter_etablissements_directeur_and_more",
        ),
        ("eleves", "0003_alter_eleves_matricule"),
    ]

    operations = [
        migrations.CreateModel(
            name="Echeances",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("montant", models.PositiveIntegerField()),
                ("date_limite", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Relances",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_relance", models.DateField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("envoyée", "Envoyée"),
                            ("reçue", "Reçue"),
                            ("ignorée", "Ignorée"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "echeance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scolarites.echeances",
                    ),
                ),
                (
                    "inscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eleves.inscriptions",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Paiements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.PositiveIntegerField()),
                ("date_paiement", models.DateField()),
                (
                    "mode_paiement",
                    models.CharField(
                        choices=[
                            ("especes", "Espèces"),
                            ("mobile_money", "Mobile Money"),
                            ("virement", "Virement bancaire"),
                            ("cheque", "Chèque"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "numero_transaction",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "justificatif",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=scolarites.models.paiement_justificatif_path,
                    ),
                ),
                ("observations", models.TextField(blank=True, null=True)),
                (
                    "statut_validation",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente de validation"),
                            ("valide", "Validé"),
                            ("rejete", "Rejeté"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("date_validation", models.DateTimeField(blank=True, null=True)),
                (
                    "echeance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scolarites.echeances",
                    ),
                ),
                (
                    "inscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eleves.inscriptions",
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paiements_valides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_paiement"],
            },
        ),
        migrations.CreateModel(
            name="PaiementHistoriques",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                (
                    "ancien_statut",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "nouveau_statut",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("ancien_montant", models.PositiveIntegerField(blank=True, null=True)),
                ("nouveau_montant", models.PositiveIntegerField(blank=True, null=True)),
                ("date_action", models.DateTimeField(auto_now_add=True)),
                ("commentaire", models.TextField(blank=True, null=True)),
                (
                    "paiement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historiques",
                        to="scolarites.paiements",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModalitePaiements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("nombre_echeances", models.PositiveIntegerField()),
                ("applicable_aux_non_affectes", models.BooleanField(default=False)),
                (
                    "annee_scolaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cores.anneescolaires",
                    ),
                ),
                (
                    "etablissement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="etablissements.etablissements",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="echeances",
            name="modalite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="scolarites.modalitepaiements",
            ),
        ),
    ]
