# Generated by Django 4.2.2 on 2025-05-05 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "etablissements",
            "0003_typeetablissement_alter_etablissements_directeur_and_more",
        ),
        ("scolarites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="modalitepaiements",
            name="niveau",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="etablissements.niveaux",
            ),
        ),
    ]
