# Generated by Django 4.2.2 on 2025-05-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scolarites", "0002_modalitepaiements_niveau"),
    ]

    operations = [
        migrations.AddField(
            model_name="modalitepaiements",
            name="montant",
            field=models.PositiveIntegerField(
                help_text="Montant total à payer pour cette modalité", null=True
            ),
        ),
    ]
