# Generated by Django 4.2.2 on 2025-05-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scolarites", "0003_modalitepaiements_montant"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="modalitepaiements",
            constraint=models.UniqueConstraint(
                fields=("etablissement", "annee_scolaire", "niveau"),
                name="unique_modalite_par_etablissement_annee_niveau",
            ),
        ),
    ]
