# Generated by Django 4.2.2 on 2025-05-06 14:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "scolarites",
            "0004_modalitepaiements_unique_modalite_par_etablissement_annee_niveau",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Relances",
        ),
    ]
