# Generated by Django 4.2.2 on 2025-05-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scolarites", "0005_delete_relances"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paiements",
            name="statut_validation",
            field=models.CharField(
                choices=[
                    ("en_attente", "En attente de validation"),
                    ("valide", "Validé"),
                    ("rejete", "Rejeté"),
                    ("partiel", "Partiel"),
                ],
                default="en_attente",
                max_length=20,
            ),
        ),
    ]
