# Generated by Django 4.2.2 on 2025-05-31 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import scolarites.models


class Migration(migrations.Migration):
    dependencies = [
        ("cores", "0003_alter_anneescolaires_libelle"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("eleves", "0018_alter_evenementscolaire_annee_scolaire"),
        ("etablissements", "0006_alter_emploitemps_professeur_and_more"),
        ("scolarites", "0006_alter_paiements_statut_validation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModaliteCantines",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "montant",
                    models.PositiveIntegerField(
                        help_text="Montant total à payer pour cette modalité", null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModaliteTransports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "montant",
                    models.PositiveIntegerField(
                        help_text="Montant total à payer pour cette modalité", null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mois",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mois", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PaiementCantinesHistoriques",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                (
                    "ancien_statut",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "nouveau_statut",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("ancien_montant", models.PositiveIntegerField(blank=True, null=True)),
                ("nouveau_montant", models.PositiveIntegerField(blank=True, null=True)),
                ("date_action", models.DateTimeField(auto_now_add=True)),
                ("commentaire", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PaiementMobileEnAttente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                ("transaction_id", models.CharField(max_length=100, unique=True)),
                (
                    "statut_validation",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("valide", "Valide"),
                            ("annule", "Annulé"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_validation", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PaiementsCantines",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.PositiveIntegerField()),
                ("date_paiement", models.DateField()),
                (
                    "mode_paiement",
                    models.CharField(
                        choices=[
                            ("especes", "Espèces"),
                            ("mobile_money", "Mobile Money"),
                            ("virement", "Virement bancaire"),
                            ("cheque", "Chèque"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "numero_transaction",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "justificatif",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=scolarites.models.paiement_justificatif_path,
                    ),
                ),
                ("observations", models.TextField(blank=True, null=True)),
                (
                    "statut_validation",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente de validation"),
                            ("valide", "Validé"),
                            ("rejete", "Rejeté"),
                            ("partiel", "Partiel"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("date_validation", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-date_paiement"],
            },
        ),
        migrations.CreateModel(
            name="PaiementsTransports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.PositiveIntegerField()),
                ("date_paiement", models.DateField()),
                (
                    "mode_paiement",
                    models.CharField(
                        choices=[
                            ("especes", "Espèces"),
                            ("mobile_money", "Mobile Money"),
                            ("virement", "Virement bancaire"),
                            ("cheque", "Chèque"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "numero_transaction",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "justificatif",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=scolarites.models.paiement_justificatif_path,
                    ),
                ),
                ("observations", models.TextField(blank=True, null=True)),
                (
                    "statut_validation",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente de validation"),
                            ("valide", "Validé"),
                            ("rejete", "Rejeté"),
                            ("partiel", "Partiel"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("date_validation", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-date_paiement"],
            },
        ),
        migrations.CreateModel(
            name="PaiementTransportHistoriques",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                (
                    "ancien_statut",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "nouveau_statut",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("ancien_montant", models.PositiveIntegerField(blank=True, null=True)),
                ("nouveau_montant", models.PositiveIntegerField(blank=True, null=True)),
                ("date_action", models.DateTimeField(auto_now_add=True)),
                ("commentaire", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="modalitepaiements",
            name="unique_modalite_par_etablissement_annee_niveau",
        ),
        migrations.AddConstraint(
            model_name="modalitepaiements",
            constraint=models.UniqueConstraint(
                fields=(
                    "etablissement",
                    "annee_scolaire",
                    "niveau",
                    "applicable_aux_non_affectes",
                ),
                name="unique_modalite_par_etablissement_annee_niveau_applicable_aux_non_affectes",
            ),
        ),
        migrations.AddField(
            model_name="paiementtransporthistoriques",
            name="paiement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historiques",
                to="scolarites.paiementstransports",
            ),
        ),
        migrations.AddField(
            model_name="paiementtransporthistoriques",
            name="utilisateur",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paiementstransports",
            name="echeance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="scolarites.modalitetransports",
            ),
        ),
        migrations.AddField(
            model_name="paiementstransports",
            name="inscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="eleves.inscriptions"
            ),
        ),
        migrations.AddField(
            model_name="paiementstransports",
            name="valide_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paiements_transports_valides",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paiementscantines",
            name="echeance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="scolarites.modalitecantines",
            ),
        ),
        migrations.AddField(
            model_name="paiementscantines",
            name="inscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="eleves.inscriptions"
            ),
        ),
        migrations.AddField(
            model_name="paiementscantines",
            name="valide_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paiements_cantines_valides",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paiementmobileenattente",
            name="echeance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="scolarites.echeances"
            ),
        ),
        migrations.AddField(
            model_name="paiementmobileenattente",
            name="inscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="eleves.inscriptions"
            ),
        ),
        migrations.AddField(
            model_name="paiementcantineshistoriques",
            name="paiement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historiques",
                to="scolarites.paiementscantines",
            ),
        ),
        migrations.AddField(
            model_name="paiementcantineshistoriques",
            name="utilisateur",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="modalitetransports",
            name="annee_scolaire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cores.anneescolaires"
            ),
        ),
        migrations.AddField(
            model_name="modalitetransports",
            name="etablissement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="etablissements.etablissements",
            ),
        ),
        migrations.AddField(
            model_name="modalitetransports",
            name="mois",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="scolarites.mois",
            ),
        ),
        migrations.AddField(
            model_name="modalitecantines",
            name="annee_scolaire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cores.anneescolaires"
            ),
        ),
        migrations.AddField(
            model_name="modalitecantines",
            name="etablissement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="etablissements.etablissements",
            ),
        ),
        migrations.AddField(
            model_name="modalitecantines",
            name="mois",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="scolarites.mois",
            ),
        ),
        migrations.AddConstraint(
            model_name="modalitetransports",
            constraint=models.UniqueConstraint(
                fields=("etablissement", "annee_scolaire", "mois"),
                name="unique_modalite_transport_par_etablissement_annee_mois",
            ),
        ),
        migrations.AddConstraint(
            model_name="modalitecantines",
            constraint=models.UniqueConstraint(
                fields=("etablissement", "annee_scolaire", "mois"),
                name="unique_modalite_cantine_par_etablissement_annee_mois",
            ),
        ),
    ]
