# Generated by Django 4.2.2 on 2025-06-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scolarites", "0007_modalitecantines_modalitetransports_mois_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paiements",
            name="mode_paiement",
            field=models.CharField(
                choices=[("especes", "Espèces"), ("virement", "B.Free")], max_length=20
            ),
        ),
    ]
