# Generated by Django 4.2.2 on 2025-06-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scolarites", "0008_alter_paiements_mode_paiement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paiementscantines",
            name="mode_paiement",
            field=models.CharField(
                choices=[("especes", "Espèces"), ("virement", "B.Free")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="paiementstransports",
            name="mode_paiement",
            field=models.CharField(
                choices=[("especes", "Espèces"), ("virement", "B.Free")], max_length=20
            ),
        ),
    ]
