# Generated by Django 4.2.2 on 2025-05-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actualites",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("contenu", models.TextField()),
                ("date_publication", models.DateField(auto_now_add=True)),
                (
                    "cible",
                    models.CharField(
                        choices=[
                            ("tous", "Tous"),
                            ("parents", "Parents"),
                            ("personnel", "Personnel"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="actualites/"),
                ),
                (
                    "fichier",
                    models.FileField(
                        blank=True, null=True, upload_to="actualites_fichiers/"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date_publication"],
            },
        ),
    ]
