# Generated by Django 4.2.2 on 2025-05-03 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Affectation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MutationPersonnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_mutation", models.DateField()),
                ("motif", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Personnels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_complet", models.CharField(max_length=150)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="personnel/"),
                ),
                ("date_embauche", models.DateField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("muté", "Muté"),
                            ("sorti", "Sorti"),
                        ],
                        max_length=20,
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Postes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Enseignants",
            fields=[
                (
                    "personnels_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="enseignants.personnels",
                    ),
                ),
                ("specialite", models.CharField(max_length=100)),
            ],
            bases=("enseignants.personnels",),
        ),
        migrations.CreateModel(
            name="TenueDeClasse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "annee_scolaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cores.anneescolaires",
                    ),
                ),
            ],
        ),
    ]
