# Generated by Django 4.2.2 on 2025-05-03 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("enseignants", "0001_initial"),
        ("etablissements", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cores", "0001_initial"),
        ("matieres", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenuedeclasse",
            name="classe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="etablissements.classes"
            ),
        ),
        migrations.AddField(
            model_name="personnels",
            name="etablissement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="etablissements.etablissements",
            ),
        ),
        migrations.AddField(
            model_name="personnels",
            name="poste",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="enseignants.postes",
            ),
        ),
        migrations.AddField(
            model_name="personnels",
            name="utilisateur",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="mutationpersonnel",
            name="etablissement_destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mutations_recues",
                to="etablissements.etablissements",
            ),
        ),
        migrations.AddField(
            model_name="mutationpersonnel",
            name="etablissement_source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mutations_envoyees",
                to="etablissements.etablissements",
            ),
        ),
        migrations.AddField(
            model_name="mutationpersonnel",
            name="personnel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="enseignants.personnels"
            ),
        ),
        migrations.AddField(
            model_name="affectation",
            name="annee_scolaire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cores.anneescolaires"
            ),
        ),
        migrations.AddField(
            model_name="affectation",
            name="classe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="etablissements.classes"
            ),
        ),
        migrations.AddField(
            model_name="affectation",
            name="matiere",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="matieres.matieres"
            ),
        ),
        migrations.AddField(
            model_name="tenuedeclasse",
            name="enseignant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="enseignants.enseignants",
            ),
        ),
        migrations.AddField(
            model_name="affectation",
            name="enseignant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="enseignants.enseignants",
            ),
        ),
    ]
