# Generated by Django 4.2.2 on 2025-05-05 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("enseignants", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="personnels",
            options={"verbose_name": "Personnel", "verbose_name_plural": "Personnels"},
        ),
        migrations.AlterField(
            model_name="personnels",
            name="poste",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="enseignants.postes",
            ),
        ),
        migrations.AlterField(
            model_name="personnels",
            name="statut",
            field=models.CharField(
                choices=[("actif", "Actif"), ("muté", "Muté"), ("sorti", "Sorti")],
                default="actif",
                max_length=20,
            ),
        ),
    ]
