# Generated by Django 4.2.2 on 2025-05-05 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "etablissements",
            "0003_typeetablissement_alter_etablissements_directeur_and_more",
        ),
        (
            "enseignants",
            "0003_alter_personnels_options_alter_personnels_poste_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="personnels",
            name="etablissement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="etablissements.etablissements",
            ),
        ),
    ]
