# Generated by Django 4.2.2 on 2025-05-16 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("enseignants", "0004_alter_personnels_etablissement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenuedeclasse",
            name="enseignant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="enseignants.personnels"
            ),
        ),
    ]
