# Generated by Django 4.2.2 on 2025-05-16 16:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("enseignants", "0005_alter_tenuedeclasse_enseignant"),
    ]

    operations = [
        migrations.RenameField(
            model_name="affectation",
            old_name="enseignant",
            new_name="professseur",
        ),
    ]
