# Generated by Django 4.2.2 on 2025-06-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enseignants", "0006_rename_enseignant_affectation_professseur"),
    ]

    operations = [
        migrations.AddField(
            model_name="postes",
            name="role_attache",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
